### DISCUSSION TITLE
Where set the value for mail and MailHog ?

### DISCUSSION THREAD

**Discussion by anivard** [locokit/locokit#372] [Q&A]
Hello,

From the doc https://docs.locokit.io/advanced/env-vars.html
I don't understand where I should set the variable for email settings.

Difference between a YAML file and a configuration file.

```
MAIL_PORT=1025
MAIL_SERVER=localhost
MAIL_USERNAME=

```

```
 lck-mail:
    image: mailhog/mailhog:latest
    environment:
      MH_STORAGE: maildir
```

Thank you

Sorry, should move to "Discussions"

**Comment by mdartic** [comment]
Hello,

I guess you're on a 0.x version (actually, there is also a 1.x in alpha testing).

For the backend, variable file is here : https://github.com/locokit/locokit/blob/main/api/.env.example

You can see there is the `MAIL_XXX` vars in it.

Mailhog is provided in the docker-compose file but is not configured to really send emails. It's a mail catcher.
Nevertheless you can configure it to send mails (see https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md#outgoing-smtp-configuration).

Another tool you could use is [mailpit](https://mailpit.axllent.org/), better UX, maybe more features, and you can configure it to send mails too.

Last configuration (the one we use in production) is to set the `MAIL_XXX` vars to use a true SMTP server, not a catcher.

To sum up, if you need to configure your backend server to allow it sending email, 
you don’t necessarily need a mailhog image, and you can directly use a SMTP server (from your infra or elsewhere).

Does it help you ?

**Reply by mdartic** [reply]
I forget to mention that the section 

```
 lck-mail:
    image: mailhog/mailhog:latest
    environment:
      MH_STORAGE: maildir
```

is to set up the `mailhog` image.

These vars are the environment vars for `mailhog`, not to explain to the backend server which SMTP server to use.
