### ISSUE TITLE
Where set the value for mail and MailHog ?

### ISSUE THREAD

**Issue by anivard** [locokit/locokit#371]
Hello,

From the doc https://docs.locokit.io/advanced/env-vars.html
I don't understand where I should set the variable for email settings.

Difference between a YAML file and a configuration file.

```
MAIL_PORT=1025
MAIL_SERVER=localhost
MAIL_USERNAME=

```

```
 lck-mail:
    image: mailhog/mailhog:latest
    environment:
      MH_STORAGE: maildir
```

Thank you
